# Generated by Django 2.0.6 on 2018-06-28 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180627_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': '账号', 'verbose_name_plural': '账号'},
        ),
    ]
