# Generated by Django 2.0.6 on 2018-06-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180628_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='admin_level',
            field=models.IntegerField(default=2),
        ),
    ]
