# Generated by Django 2.0.6 on 2018-06-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_myuser_admin_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='parent_id',
            field=models.IntegerField(default=0),
        ),
    ]
