# Generated by Django 2.0.6 on 2018-07-03 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_myuser_parent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='date_of_birth',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='email',
            new_name='phone_number',
        ),
    ]
