# Generated by Django 2.0.6 on 2018-07-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180703_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='job',
            field=models.IntegerField(choices=[(0, '管理员'), (1, '网络客服主管'), (2, '网络客服'), (3, '前台'), (4, '咨询师'), (5, '美容师')], default=0, verbose_name='职位'),
        ),
    ]
