# Generated by Django 2.0.6 on 2018-07-21 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('state', models.IntegerField(choices=[(0, '未到店'), (1, '已到店'), (2, '新单'), (3, '已完成')], default=0, verbose_name='状态')),
                ('sex', models.CharField(default='', max_length=20, verbose_name='性别')),
                ('age', models.CharField(default='', max_length=20, verbose_name='年龄')),
                ('constellation', models.CharField(default='', max_length=20, verbose_name='星座')),
                ('address', models.CharField(default='', max_length=50, verbose_name='住址')),
                ('job', models.CharField(default='', max_length=20, verbose_name='职业')),
                ('order_date', models.DateField(null=True, verbose_name='预约日期')),
                ('ill_place', models.CharField(default='', max_length=50, verbose_name='患病部位')),
                ('ill_time', models.CharField(default='', max_length=20, verbose_name='患病时间')),
                ('ill_kind', models.CharField(default='', max_length=50, verbose_name='患病种类')),
            ],
            options={
                'verbose_name': '客户信息',
                'verbose_name_plural': '客户信息列表',
            },
        ),
    ]
