# Generated by Django 2.0.6 on 2018-07-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='住址'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='constellation',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='星座'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ill_kind',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='患病种类'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ill_place',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='患病部位'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ill_time',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='患病时间'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='job',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='职业'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sex',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.IntegerField(choices=[(0, '未到店'), (1, '已到店'), (2, '新单'), (3, '已完成')], default=0, null=True, verbose_name='状态'),
        ),
    ]
