# Generated by Django 2.0.6 on 2018-07-21 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20180721_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='住址'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='constellation',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='星座'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ill_kind',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='患病种类'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ill_place',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='患病部位'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ill_time',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='患病时间'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='job',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='职业'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='预约日期'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sex',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.IntegerField(choices=[(0, '未到店'), (1, '已到店'), (2, '新单'), (3, '已完成')], default=0, verbose_name='状态'),
        ),
    ]
