# Generated by Django 2.0.6 on 2018-07-21 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20180719_1126'),
        ('store', '0005_customer_web_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='web_staff', to='organization.LastStore', verbose_name='网络客服'),
        ),
    ]
