# Generated by Django 2.0.6 on 2018-07-22 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20180721_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer2',
            fields=[
            ],
            options={
                'verbose_name': '客户信息_前台',
                'verbose_name_plural': '客户信息_前台',
                'proxy': True,
                'indexes': [],
            },
            bases=('store.customer',),
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '客户信息', 'verbose_name_plural': '客户信息'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='web_staff', to='organization.LastStore', verbose_name='门店'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='web_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='web_staff', to=settings.AUTH_USER_MODEL, verbose_name='网络客服'),
        ),
    ]
