# Generated by Django 2.0.6 on 2018-07-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20180722_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_from_web',
            field=models.BooleanField(default=True, editable=False, verbose_name='是否由网络客服录入'),
        ),
    ]
