# Generated by Django 2.0.6 on 2018-07-24 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0009_customer_is_from_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='front_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='所属前台'),
        ),
    ]
