# Generated by Django 2.0.6 on 2018-07-24 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0010_customer_front_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='beauty_consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='beauty_consultant', to=settings.AUTH_USER_MODEL, verbose_name='分配美容咨询师'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='front_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='front_staff', to=settings.AUTH_USER_MODEL, verbose_name='所属前台'),
        ),
    ]
