# Generated by Django 2.0.6 on 2018-07-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20180724_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='back_date',
            field=models.DateField(blank=True, null=True, verbose_name='回访日期'),
        ),
    ]
