# Generated by Django 2.0.6 on 2018-07-31 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_customer_back_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer3',
            fields=[
            ],
            options={
                'verbose_name': '设置客户回访',
                'verbose_name_plural': '设置客户回访',
                'proxy': True,
                'indexes': [],
            },
            bases=('store.customer',),
        ),
        migrations.CreateModel(
            name='Customer4',
            fields=[
            ],
            options={
                'verbose_name': '今日所需回访',
                'verbose_name_plural': '今日所需回访',
                'proxy': True,
                'indexes': [],
            },
            bases=('store.customer',),
        ),
        migrations.CreateModel(
            name='Customer5',
            fields=[
            ],
            options={
                'verbose_name': '客户信息_咨询师',
                'verbose_name_plural': '客户信息_咨询师',
                'proxy': True,
                'indexes': [],
            },
            bases=('store.customer',),
        ),
    ]
