# Generated by Django 2.0.6 on 2018-08-03 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20180803_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='register_date',
        ),
        migrations.AddField(
            model_name='customer',
            name='order_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='预约时间'),
        ),
        migrations.AddField(
            model_name='customer',
            name='register_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='登记时间'),
        ),
    ]
