# Generated by Django 2.0.6 on 2018-08-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_customer_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='area',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='区域'),
        ),
    ]
