# Generated by Django 2.0.6 on 2018-08-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_customer_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='咨询备注'),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号2'),
        ),
    ]
