# Generated by Django 2.0.6 on 2018-08-11 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20180811_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='back_note',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='回访备注'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='咨询备注'),
        ),
    ]
