# Generated by Django 2.0.6 on 2018-08-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20180811_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.IntegerField(blank=True, choices=[(0, '男'), (1, '女')], default='', verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='咨询备注'),
        ),
    ]
