# Generated by Django 2.0.6 on 2018-08-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20180814_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AddField(
            model_name='customer',
            name='channel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='渠道'),
        ),
        migrations.AddField(
            model_name='customer',
            name='client',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='客户端'),
        ),
        migrations.AddField(
            model_name='customer',
            name='we_num',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='微信号码'),
        ),
    ]
