# Generated by Django 2.0.6 on 2018-08-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_auto_20180815_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='order_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='预约时间'),
        ),
    ]
