# Generated by Django 2.0.6 on 2018-08-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20180815_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(0, '男'), (1, '女')], default=0, null=True, verbose_name='性别'),
        ),
    ]
