# Generated by Django 2.0.6 on 2018-08-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20180815_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='channel',
            field=models.IntegerField(blank=True, choices=[(0, '抖音'), (1, '微博'), (2, '团购')], null=True, verbose_name='渠道'),
        ),
    ]
