# Generated by Django 2.0.6 on 2018-08-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_auto_20180815_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='constellation',
            field=models.IntegerField(blank=True, choices=[(0, '白羊座'), (1, '金牛座'), (2, '双子座'), (3, '巨蟹座'), (4, '狮子座'), (5, '处女座'), (6, '天秤座'), (7, '天蝎座'), (8, '射手座'), (9, '摩羯座'), (10, '水瓶座'), (11, '双鱼座')], default=0, verbose_name='星座'),
        ),
    ]
