# Generated by Django 2.0.6 on 2018-08-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_auto_20180816_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='arrive_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='到店时间'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='channel',
            field=models.IntegerField(blank=True, choices=[(0, '抖音'), (1, '微博'), (2, '团购'), (999, '请选择')], default=999, null=True, verbose_name='渠道'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='constellation',
            field=models.IntegerField(blank=True, choices=[(0, '白羊座'), (1, '金牛座'), (2, '双子座'), (3, '巨蟹座'), (4, '狮子座'), (5, '处女座'), (6, '天秤座'), (7, '天蝎座'), (8, '射手座'), (9, '摩羯座'), (10, '水瓶座'), (11, '双鱼座'), (999, '请选择')], default=999, verbose_name='星座'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='register_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='登记时间'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(0, '男'), (1, '女'), (999, '请选择')], default=999, null=True, verbose_name='性别'),
        ),
    ]
