# Generated by Django 2.0.6 on 2018-08-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_auto_20180816_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='order_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='预约到店时间'),
        ),
    ]
