# Generated by Django 2.0.6 on 2018-07-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000, verbose_name='通知消息')),
            ],
            options={
                'verbose_name': '  通知消息',
                'verbose_name_plural': '  通知消息',
            },
        ),
    ]
