# Generated by Django 2.0.6 on 2018-08-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='message',
            field=models.CharField(max_length=1000, verbose_name='消息内容'),
        ),
    ]
