# Generated by Django 2.0.6 on 2018-07-02 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0002_provinceagent_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityagent',
            name='admin_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_org1', to=settings.AUTH_USER_MODEL, verbose_name='管理员'),
        ),
        migrations.AddField(
            model_name='laststore',
            name='admin_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_org2', to=settings.AUTH_USER_MODEL, verbose_name='管理员'),
        ),
    ]
