# Generated by Django 2.0.6 on 2018-07-19 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20180702_2045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cityagent',
            options={'verbose_name': '  市代', 'verbose_name_plural': '  市代'},
        ),
        migrations.AlterModelOptions(
            name='headstore',
            options={'verbose_name': '    总店', 'verbose_name_plural': '    总店'},
        ),
        migrations.AlterModelOptions(
            name='laststore',
            options={'verbose_name': ' 门店', 'verbose_name_plural': ' 门店'},
        ),
        migrations.AlterModelOptions(
            name='provinceagent',
            options={'verbose_name': '   省代', 'verbose_name_plural': '   省代'},
        ),
    ]
