# Generated by Django 2.0.6 on 2018-07-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pName', models.CharField(max_length=30, null=True, verbose_name='产品名')),
                ('pprice', models.CharField(max_length=30, null=True, verbose_name='价格')),
                ('pnumber', models.IntegerField()),
            ],
            options={
                'verbose_name': '产品录入',
                'verbose_name_plural': '产品录入',
            },
        ),
    ]
