# Generated by Django 2.0.6 on 2018-07-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitems',
            name='pnumber',
            field=models.IntegerField(verbose_name='数量'),
        ),
    ]
