# Generated by Django 2.0.5 on 2018-08-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('product', '0002_auto_20180727_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_name', models.CharField(max_length=30, null=True, verbose_name='器械名')),
                ('instrument_steps', models.ManyToManyField(to='items.Step')),
            ],
        ),
        migrations.AddField(
            model_name='productitems',
            name='steps',
            field=models.ManyToManyField(to='items.Step'),
        ),
    ]
