# Generated by Django 2.0.6 on 2018-08-11 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20180811_1008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='productItems',
            new_name='Product',
        ),
    ]
