# Generated by Django 2.0.5 on 2018-08-17 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0031_auto_20180817_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='back_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('back_data', models.DateField(blank=True, null=True, verbose_name='回访日期')),
                ('back_state', models.BooleanField(default=False, verbose_name='回访状态')),
                ('service_phon', models.CharField(max_length=255, unique=True, verbose_name='手机号')),
                ('back_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_name', to='store.Customer', verbose_name='客户姓名')),
            ],
        ),
        migrations.CreateModel(
            name='back_plan1',
            fields=[
            ],
            options={
                'verbose_name': '添加回访计划',
                'verbose_name_plural': '添加回访计划',
                'proxy': True,
                'indexes': [],
            },
            bases=('returnvisit.back_plan',),
        ),
    ]
