# Generated by Django 2.0.5 on 2018-08-17 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('returnvisit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='back_plan',
            options={'verbose_name': '客户回访', 'verbose_name_plural': '客户回访'},
        ),
    ]
