# Generated by Django 2.0.5 on 2018-08-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returnvisit', '0002_auto_20180817_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='back_plan',
            name='service_phon',
            field=models.CharField(max_length=255, verbose_name='手机号'),
        ),
    ]
