# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-27 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PRODUCT_CARTYPE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=32)),
                ('car_info', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='VIN_PRODUCT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin_code', models.CharField(max_length=8)),
                ('product_code', models.CharField(max_length=32)),
            ],
        ),
    ]
