# Generated by Django 2.0.6 on 2018-06-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vin_search', '0002_auto_20180618_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vin_product',
            name='vin_code',
            field=models.CharField(max_length=8, verbose_name='vin码'),
        ),
    ]
