# Generated by Django 2.0.5 on 2018-08-06 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30, null=True, verbose_name='项目名')),
                ('item_price', models.IntegerField(null=True, verbose_name='价格')),
                ('frequency', models.IntegerField(null=True, verbose_name='价格')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_content', models.CharField(max_length=1000, null=True)),
                ('belong_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='items.Item', verbose_name='所属项目')),
            ],
        ),
    ]
