# Generated by Django 2.0.6 on 2018-08-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='step_num',
            field=models.IntegerField(null=True, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='item',
            name='frequency',
            field=models.IntegerField(null=True, verbose_name='次数'),
        ),
    ]
