# Generated by Django 2.0.6 on 2018-08-11 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20180811_1010'),
        ('items', '0002_auto_20180809_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.Instrument', verbose_name='仪器')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='items.Item', verbose_name='所属项目')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(null=True, verbose_name='序号')),
                ('num', models.IntegerField(null=True, verbose_name='数量')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='items.Item', verbose_name='所属项目')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.Product', verbose_name='产品')),
            ],
        ),
    ]
