# Generated by Django 2.0.6 on 2018-08-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_instrument_item_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_instrument',
            name='step',
            field=models.IntegerField(null=True, verbose_name='序号'),
        ),
    ]
