# Generated by Django 2.0.6 on 2018-08-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_instrument_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='classify',
            field=models.CharField(max_length=30, null=True, verbose_name='项目类别'),
        ),
        migrations.AddField(
            model_name='item_instrument',
            name='time',
            field=models.IntegerField(null=True, verbose_name='用时'),
        ),
        migrations.AddField(
            model_name='item_product',
            name='time',
            field=models.IntegerField(null=True, verbose_name='用时'),
        ),
    ]
