# Generated by Django 2.0.5 on 2018-08-19 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pName', models.CharField(max_length=30, null=True, verbose_name='商品名称')),
                ('pNumber', models.IntegerField(blank=True, null=True)),
                ('unitPrice', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(max_length=30, null=True, verbose_name='单位')),
                ('pType', models.CharField(max_length=30, null=True, verbose_name='类型')),
                ('handManName', models.CharField(max_length=30, null=True)),
                ('handManPhone', models.CharField(max_length=30, null=True)),
                ('orderDate', models.DateTimeField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('totalPrice', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record_transfer_library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pName', models.CharField(max_length=30, null=True)),
                ('pNumber', models.IntegerField(blank=True, null=True)),
                ('unitPrice', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(max_length=30, null=True)),
                ('totalPrice', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(max_length=30, null=True)),
                ('handManName', models.CharField(max_length=30, null=True)),
                ('handManPhone', models.CharField(max_length=30, null=True)),
                ('trasfer_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sName', models.CharField(max_length=30, null=True, verbose_name='供应商名称')),
                ('companyPhone', models.CharField(max_length=30, null=True)),
                ('contactPeople', models.CharField(max_length=30, null=True)),
                ('contactPhone', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WareHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wName', models.CharField(max_length=30, null=True, verbose_name='仓库名称')),
                ('wState', models.CharField(max_length=30, null=True, verbose_name='仓库状态')),
                ('build_WareHouse_time', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='record_transfer_library',
            name='in_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inwname', to='Inventory_app.WareHouse'),
        ),
        migrations.AddField(
            model_name='record_transfer_library',
            name='out_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='outwname', to='Inventory_app.WareHouse'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sname', to='Inventory_app.Supplier', verbose_name='所属供应商'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='wHouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wname', to='Inventory_app.WareHouse', verbose_name='所属仓库'),
        ),
    ]
