# Generated by Django 2.0.6 on 2018-08-13 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.FloatField(verbose_name='折扣')),
            ],
            options={
                'verbose_name': '折扣录入',
                'verbose_name_plural': '折扣录入',
            },
        ),
    ]
